export const CartActionTypes = {
	TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
	ADD_ITEM: 'ADD_ITEM',
	INCREMENT_ITEM_QUANTITY: 'INCREMENT_ITEM_QUANTITY',
	DECREMENT_ITEM_QUANTITY: 'DECREMENT_ITEM_QUANTITY',
	REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
}
